config/routes.rb
# Rails.application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
#   resources :comments
#   resources :meal_posts
#   resources :users
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
#   # Can be used by load balancers and uptime monitors to verify that the app is live.
#   get "up" => "rails/health#show", as: :rails_health_check

#   # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
#   # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
#   # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

#   # Defines the root path route ("/")
#   # root "posts#index"
# end
Rails.application.routes.draw do
  root "meal_posts#index"

  resources :users
  resources :meal_posts do
    resources :comments, only: [ :create, :destroy ]
  end

  resources :likes, only: [ :create, :destroy ]
  resources :bookmarks, only: [ :create, :destroy ]

  # Session controller
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/meal_post.rb
class MealPost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  # Active Storage
  has_one_attached :image

  enum meal_type: { breakfast: 0, lunch: 1, dinner: 2 }
  enum source_type: { homemade: 0, eating_out: 1 }

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/meal_posts_controller.rb
class MealPostsController < ApplicationController
  before_action :set_meal_post, only: %i[ show edit update destroy ]

  # GET /meal_posts or /meal_posts.json
  def index
    @meal_posts = MealPost.all
  end

  # GET /meal_posts/1 or /meal_posts/1.json
  def show
  end

  # GET /meal_posts/new
  def new
    @meal_post = MealPost.new
  end

  # GET /meal_posts/1/edit
  def edit
  end

  # POST /meal_posts or /meal_posts.json
  def create
    @meal_post = MealPost.new(meal_post_params)

    respond_to do |format|
      if @meal_post.save
        format.html { redirect_to @meal_post, notice: "Meal post was successfully created." }
        format.json { render :show, status: :created, location: @meal_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_posts/1 or /meal_posts/1.json
  def update
    respond_to do |format|
      if @meal_post.update(meal_post_params)
        format.html { redirect_to @meal_post, notice: "Meal post was successfully updated." }
        format.json { render :show, status: :ok, location: @meal_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_posts/1 or /meal_posts/1.json
  def destroy
    @meal_post.destroy!

    respond_to do |format|
      format.html { redirect_to meal_posts_path, status: :see_other, notice: "Meal post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_post
      @meal_post = MealPost.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def meal_post_params
      params.expect(meal_post: [ :title, :content, :meal_type, :source_type, :user_id ])
    end
end

app/helpers/meal_posts_helper.rb
module MealPostsHelper
end

app/views/meal_posts/_form.html.erb
<%= form_with(model: meal_post) do |form| %>
  <% if meal_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meal_post.errors.count, "error") %> prohibited this meal_post from being saved:</h2>

      <ul>
        <% meal_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :meal_type, style: "display: block" %>
    <%= form.number_field :meal_type %>
  </div>

  <div>
    <%= form.label :source_type, style: "display: block" %>
    <%= form.number_field :source_type %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meal_posts/_meal_post.html.erb
<div id="<%= dom_id meal_post %>">
  <p>
    <strong>Title:</strong>
    <%= meal_post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= meal_post.content %>
  </p>

  <p>
    <strong>Meal type:</strong>
    <%= meal_post.meal_type %>
  </p>

  <p>
    <strong>Source type:</strong>
    <%= meal_post.source_type %>
  </p>

  <p>
    <strong>User:</strong>
    <%= meal_post.user_id %>
  </p>

</div>

app/views/meal_posts/edit.html.erb
<% content_for :title, "Editing meal post" %>

<h1>Editing meal post</h1>

<%= render "form", meal_post: @meal_post %>

<br>

<div>
  <%= link_to "Show this meal post", @meal_post %> |
  <%= link_to "Back to meal posts", meal_posts_path %>
</div>

app/views/meal_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Meal posts" %>

<h1>Meal posts</h1>

<div id="meal_posts">
  <% @meal_posts.each do |meal_post| %>
    <%= render meal_post %>
    <p>
      <%= link_to "Show this meal post", meal_post %>
    </p>
  <% end %>
</div>

<%= link_to "New meal post", new_meal_post_path %>

app/views/meal_posts/new.html.erb
<% content_for :title, "New meal post" %>

<h1>New meal post</h1>

<%= render "form", meal_post: @meal_post %>

<br>

<div>
  <%= link_to "Back to meal posts", meal_posts_path %>
</div>

app/views/meal_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meal_post %>

<div>
  <%= link_to "Edit this meal post", edit_meal_post_path(@meal_post) %> |
  <%= link_to "Back to meal posts", meal_posts_path %>

  <%= button_to "Destroy this meal post", @meal_post, method: :delete %>
</div>